const fs = require('fs');

const f1 = 'c:/entraiot-production-final/entraiot-unified/stage1/assets/Portfolio-CFTaDZT1.js';
let c1 = fs.readFileSync(f1, 'utf8');

const target = 'projects:[{id:"corian-exterior",title:"Microsite",desc:"DuPont<sup>™</sup> Corian<sup>®</sup> exterior cladding material",role:"Design ~ Development",tech:"Php / Gsap / Vue.js",url:"https://www.exteriors.corian.com"},{id:"dupont-airguard",title:"Microsite",logoScale:2.5,desc:"Tyvek® & AirGuard® Energy Efficiency Solution",role:"Development",tech:"Nuxt.js / Gsap",url:"https://energy-efficiency.dupont.com"},{id:"sanrita",title:"Website",desc:"A Digital Agency based in Montreal, Canada",role:"Development",tech:"Next.js / React Three Fiber / DatoCMS",url:"https://sanrita.ca"},{id:"pixila",title:"Website",desc:"My Digital Company creates custom digital solutions for ambitious brands and individuals",role:"Design ~ Development",tech:"Astro.js / React / React Three Fiber",url:"https://pixila.net"},{id:"railight",title:"SaaS Application",desc:"AI-based saas with a simple goal: adding realistic lighting to your photos!",role:"Design ~ Development",tech:"React Three Fiber",url:"https://railight.pixila.net/editor"},{id:"lab77",title:"Website",desc:"My personal lab where I showcase projects, experiments, and skills",role:"Design ~ Development",tech:"React Three Fiber",url:"https://lab77.sebastien-lempens.com"},{id:"corian-website",title:"Website",desc:"Official website of DuPont<sup>™</sup> Corian<sup>®</sup> Solid Surface",role:"Design ~ Development",tech:"Php / Gsap / Vue.js",url:"https://www.corian.com"},{id:"corian-tool",logoScale:2,title:"Web Application",desc:"DuPont<sup>™</sup> Corian<sup>®</sup> Color Web application",role:"Design ~ Development",tech:"Vue.js / Gsap",url:"https://www.colors.corian.com"},{id:"dltal",title:"landing page",desc:"Belgian Bistronomic Restaurant",role:"Logo ~ Design Web ~ Development",tech:"Next.js / Gsap",url:"https://delaterre-a-lassiette.be"},{id:"aos",logoScale:2,title:"Website",desc:"Multidisciplinary space for well-being and training",role:"Logo ~ Design ~ Development",tech:"Next.js / Gsap / Three.js (R3F)",url:"https://arboretsens.lu"},{id:"telkea-voeux-2023",logoScale:2,title:"Web Game",desc:"WebGL Christmas Game for Telkea Company",role:"Design ~ Development",tech:"Three.js (R3F)",url:"https://voeux2023.telkea.com"}]';

const replacement = 'projects:[{id:"corian-exterior",reference:"corian-exterior",title:"Department",desc:"Strategizing for the future, optimizing processes, and leading the way towards comprehensive digital transformation.",role:"Management Department",tech:"Core Strategy",url:"#"},{id:"dupont-airguard",reference:"dupont-airguard",title:"Department",logoScale:2.5,desc:"Crafting compelling narratives, engaging audiences, and driving growth through data-backed market intelligence.",role:"Marketing Department",tech:"Growth & Outreach",url:"#"},{id:"sanrita",reference:"sanrita",title:"Department",desc:"Building robust architectures, engineering innovative solutions, and pushing the boundaries of modern technology.",role:"Technical Department",tech:"Engineering & R&D",url:"#"},{id:"pixila",reference:"pixila",title:"Department",desc:"Ensuring sustainable growth, managing resources efficiently, and securing long-term economic stability.",role:"Financial Department",tech:"Operations & Finance",url:"#"},{id:"railight",reference:"railight",title:"Portal",desc:"Streamlined communication, dedicated support, and seamless project tracking for our valued partners.",role:"Client Handling Portal",tech:"Support & Success",url:"#"}]';

const idx = c1.indexOf(target);
if (idx !== -1) {
  console.log('Target found in F1, replacing...');
  c1 = c1.replace(target, replacement);
  fs.writeFileSync(f1, c1, 'utf8');
  console.log('F1 replaced successfully!');
} else {
  console.log('Target not found in F1!');
}
